import { z } from "zod";
import { CATEGORIES, PRIORITIES } from "./types";

/**
 * Strict Zod schema for the AI extraction result. Both the OpenAI-backed
 * extractor and the deterministic fallback parser return objects that satisfy
 * this schema, so the rest of the app only ever deals with validated data.
 *
 * Guardrails baked in:
 *  - dates are nullable and must be ISO `YYYY-MM-DD` when present (the model is
 *    instructed never to invent a precise date it wasn't given);
 *  - confidence is clamped to 0..1;
 *  - `missing_information` captures what Nook still needs to ask about.
 */

const isoDate = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, "must be an ISO date (YYYY-MM-DD)")
  .nullable();

export const extractionSchema = z.object({
  title: z.string().min(1).max(120),
  summary: z.string().min(1).max(400),
  category: z.enum(CATEGORIES),
  priority: z.enum(PRIORITIES),
  due_date: isoDate,
  reminder_date: isoDate,
  follow_up_date: isoDate,
  missing_information: z.array(z.string()).default([]),
  recommended_action: z.string().min(1).max(200),
  approval_required: z.boolean(),
  confidence_score: z.number().min(0).max(1),
  /** A short, supportive follow-up question — only when genuinely needed. */
  follow_up_question: z.string().nullable().default(null),
  /** True when the request is a research/shopping/decision ask. */
  is_decision: z.boolean().default(false),
  /** Parsed budget if the user named one (e.g. "under $2,000"). */
  budget: z.number().nonnegative().nullable().default(null),
  currency: z.string().length(3).default("AUD"),
});

export type Extraction = z.infer<typeof extractionSchema>;

/**
 * A single actionable reminder pulled out of a planning conversation, so a
 * checklist Nook talks through can be saved as tracked items with dates.
 */
export const plannedReminderSchema = z.object({
  title: z.string().min(1).max(120),
  date: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/)
    .nullable()
    .default(null),
  note: z.string().max(300).optional().default(""),
});
export type PlannedReminder = z.infer<typeof plannedReminderSchema>;

export const plannedRemindersSchema = z.object({
  reminders: z.array(plannedReminderSchema).max(25).default([]),
});

/**
 * A ready-to-use draft Nook prepares so the user can actually get a task done
 * (an email to send, a message, a step-by-step) rather than just tracking it.
 */
export const draftSchema = z.object({
  label: z.string().min(1).max(60),
  format: z.enum(["email", "message", "steps", "note"]).default("note"),
  body: z.string().min(1).max(3000),
});
export type Draft = z.infer<typeof draftSchema>;

/**
 * A complete, bundled shopping/decision option generated by the AI for a real
 * request. Matches the RecommendationOption shape minus the fields the store
 * fills in (id, set_id, currency, saved, rejected).
 */
export const recommendationBundleSchema = z.object({
  title: z.string().min(1).max(120),
  total_price: z.number().nonnegative(),
  is_best_match: z.boolean().default(false),
  items: z
    .array(
      z.object({
        name: z.string().min(1).max(160),
        price: z.number().nonnegative(),
        note: z.string().max(100).optional(),
      }),
    )
    .max(8)
    .default([]),
  advantages: z.array(z.string().max(160)).max(6).default([]),
  trade_offs: z.array(z.string().max(160)).max(6).default([]),
  why_it_suits: z.string().max(400),
  retailer_label: z.string().max(80),
  retailer_url: z.string().max(300),
  delivery: z.string().max(160),
  sizing_notes: z.string().max(200).nullable().default(null),
});
export type RecommendationBundle = z.infer<typeof recommendationBundleSchema>;

export const recommendationSetAISchema = z.object({
  summary: z.string().min(1).max(300),
  options: z.array(recommendationBundleSchema).min(1).max(4),
});

/** Request body accepted by POST /api/extract. */
export const extractRequestSchema = z.object({
  input: z.string().min(1, "Tell Nook something first.").max(2000),
  currency: z.string().length(3).default("AUD"),
  /** ISO date of "today" so the fallback parser can resolve relative dates. */
  today: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/)
    .optional(),
});
export type ExtractRequest = z.infer<typeof extractRequestSchema>;

export const extractResponseSchema = z.object({
  extraction: extractionSchema,
  /** "openai" or "fallback" — surfaced so the UI can label demo behaviour. */
  engine: z.enum(["openai", "fallback"]),
});
export type ExtractResponse = z.infer<typeof extractResponseSchema>;

/** Onboarding form. */
export const onboardingSchema = z.object({
  preferred_name: z.string().min(1, "What should Nook call you?").max(60),
  household_type: z.enum(["solo", "couple", "family", "shared"]),
  focus_areas: z.array(z.enum(CATEGORIES)).min(1, "Pick at least one area."),
  notification_preference: z.enum(["all", "important", "quiet"]),
  proactive_suggestions: z.boolean(),
});
export type OnboardingValues = z.infer<typeof onboardingSchema>;

/** Auth forms (demo auth — no real password checks). */
export const loginSchema = z.object({
  email: z.string().email("Enter a valid email."),
  password: z.string().min(6, "At least 6 characters."),
});
export type LoginValues = z.infer<typeof loginSchema>;

export const signupSchema = loginSchema.extend({
  name: z.string().min(1, "Enter your name.").max(60),
});
export type SignupValues = z.infer<typeof signupSchema>;
